<div class="chatlog__message-group">
  <div id="chatlog__message-container-1041325603388932167" class="chatlog__message-container" data-message-id="1041325603388932167">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/1017852452252430446/3da69f829590bda2a7e89cd5f423f4e0.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" title="jrsaruo" data-user-id="1017852452252430446">ジュニア</span> <a href="/channels/375206337937801216?category=main&amp;channel=swift-zatsu&amp;message_id=1041325603388932167"><span class="chatlog__timestamp" title="Sunday, 13 November 2022 12:16"></span></a><a href="#chatlog__message-container-1041325603388932167">11/13/2022 12:16</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">ありがとうございます<img loading="lazy" class="chatlog__emoji " alt="🙇" title="person_bowing" src="https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f647.svg"><img loading="lazy" class="chatlog__emoji " alt="🏻" title="🏻" src="https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3fb.svg">‍♂️ そうなんですよね。↓のようなテストを書いたときに怒られて気になった次第でした。 <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline language-swift">XCTContext.runActivity(named: "") { _ in // Call can throw, but it is not marked with 'try' and the error is not handled XCTAssert(try foo()) }</code></span></div>
      </div>
    </div>
  </div>
</div>