<div class="chatlog__message-group">
  <div id="chatlog__message-container-334161030701907968" class="chatlog__message-container" data-message-id="334161030701907968">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/189711109966659584/95280765d1be73ce985dce15ea3585f6.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(237,171,161)" title="omochimetaru" data-user-id="189711109966659584">omochimetaru</span> <a href="/channels/291054454793306112?category=main&amp;channel=swift&amp;message_id=334161030701907968"><span class="chatlog__timestamp" title="Tuesday, 11 July 2017 02:36"></span></a><a href="#chatlog__message-container-334161030701907968">07/11/2017 02:36</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">これってcatchした場合必ず脱出するんですよね？ それならそもそもcatchしなければ良さそうだけど、エラーを包み直したいってことですか？</span></div>
      </div>
    </div>
  </div>
</div>