<div class="chatlog__message-group">
  <div id="chatlog__message-container-432832804254908416" class="chatlog__message-container" data-message-id="432832804254908416">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/431049118421483540/718f2e1723b7d3211c3416afb97436e3.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" title="masakihori" data-user-id="431049118421483540">masakihori</span> <a href="/channels/291211035438874625?category=archived&amp;channel=beginner-help-archived&amp;message_id=432832804254908416"><span class="chatlog__timestamp" title="Monday, April 9, 2018 9:23 AM"></span></a><a href="#chatlog__message-container-432832804254908416">4/9/2018 9:23 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">例えば <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline nohighlight">func coodinator() -&gt; NSPersistentStoreCoordinator { do { return try makeCoodinator() } catch { //エラー処理　アラートを出してterminate } }</code> という関数であった場合 <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline nohighlight">func coodinator(_ f: () throws -&gt; NSPersistentStoreCoordinator) -&gt; NSPersistentStoreCoordinator { do { return try f() } catch { //エラー処理　アラートを出してterminate } }</code> にしてテスト時にthrowする関数を与えるような感じ？ だとおかしいですね... ちょっと考えてみます</span></div>
      </div>
    </div>
  </div>
</div>