<div class="chatlog__message-group">
  <div id="chatlog__message-container-432801188837195782" class="chatlog__message-container" data-message-id="432801188837195782">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/293573633035730946/08ab0592c6064f92c3674e09cc81b5da.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" title="hiragram" data-user-id="293573633035730946">hiragram</span> <a href="/channels/291211035438874625?category=main&amp;channel=beginner-help&amp;message_id=432802049974075402"><span class="chatlog__timestamp" title="Monday, 09 April 2018 07:17"></span></a><a href="#chatlog__message-container-432801188837195782">04/09/2018 07:17</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">テスト対象のコードに直接fatalError書くのやめてthrowしてcatchした所でfatalErrorするようにするくらいしか思い浮かばないけどオーバーキル感ある</span></div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-432802049974075402" class="chatlog__message-container" data-message-id="432802049974075402">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="Monday, 09 April 2018 07:20">07:20</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve"><code class="chatlog__markdown-pre chatlog__markdown-pre--multiline language-swift">enum UnrecoverableError: Error { case preconditionFailure } struct Hoge { func テストしたいメソッド() throws { if true { throw UnrecoverableError.preconditionFailure } } } let hoge = Hoge() do { try hoge.テストしたいメソッド() } catch let error as UnrecoverableError { switch error { case .preconditionFailure: preconditionFailure() } }</code> うーんやりたくない</span></div>
      </div>
    </div>
  </div>
</div>