<div class="chatlog__message-group">
  <div class="chatlog__author-avatar-container">
    <img class="chatlog__author-avatar" src="https://cdn.discordapp.com/avatars/296587674737704960/5d3c584499ce245b7129cda8c7ae00e9.png?size=128" alt="Avatar" loading="lazy">
  </div>
  <div class="chatlog__messages">
    <span class="chatlog__author-name" title="rintaro#0001" data-user-id="296587674737704960" style="">rintaro</span>
    <span class="chatlog__timestamp">03-Sep-18 06:57 AM</span>
    <div class="chatlog__message " data-message-id="486067230153506829" id="message-486067230153506829" title="Message sent: 03-Sep-18 06:57 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">
            <div class="pre pre--multiline language-swift">protocol HasInt { var intValue : Int {get set} } func mod(_ val: inout Int) throws {} func testing&lt;T: HasInt&gt;(x: inout T) throws { try mod(&amp;x.intValue) }</div>
          </span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="486067413977268224" id="message-486067413977268224" title="Message sent: 03-Sep-18 06:58 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">で、 <div class="pre pre--multiline nohighlight">// testing&lt;A&gt;(x:) sil hidden @$S4test7testing1xyxz_tKAA6HasIntRzlF : $@convention(thin) &lt;T where T : HasInt&gt; (@inout T) -&gt; @error Error { // %0 // users: %3, %1 bb0(%0 : $*T): %3 = begin_access [modify] [static] %0 : $*T // users: %11, %16, %5 %4 = witness_method $T, #HasInt.intValue!modify.1 : &lt;Self where Self : HasInt&gt; (inout Self) -&gt; () -&gt; () : $@yield_once @convention(witness_method: HasInt) &lt;τ_0_0 where τ_0_0 : HasInt&gt; (@inout τ_0_0) -&gt; @yields @inout Int // user: %5 (%5, %6) = begin_apply %4&lt;T&gt;(%3) : $@yield_once @convention(witness_method: HasInt) &lt;τ_0_0 where τ_0_0 : HasInt&gt; (@inout τ_0_0) -&gt; @yields @inout Int // users: %8, %10, %15 // function_ref mod(_:) %7 = function_ref @$S4test3modyySizKF : $@convention(thin) (@inout Int) -&gt; @error Error // user: %8 try_apply %7(%5) : $@convention(thin) (@inout Int) -&gt; @error Error, normal bb1, error bb2 // id: %8 bb1(%9 : $()): // Preds: bb0 end_apply %6 // id: %10 end_access %3 : $*T // id: %11 %12 = tuple () // user: %13 return %12 : $() // id: %13 // %14 // user: %17 bb2(%14 : $Error): // Preds: bb0 abort_apply %6 // id: %15 end_access %3 : $*T // id: %16 throw %14 : $Error // id: %17 } // end sil function '$S4test7testing1xyxz_tKAA6HasIntRzlF'</div> なので、アクセス中に throw したときみたいです。</span>
        </div>
      </div>
    </div>
  </div>
</div>