<div class="chatlog__message-group">
  <div id="chatlog__message-container-496556759385636906" class="chatlog__message-container " data-message-id="496556759385636906">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/296587674737704960/5d3c584499ce245b7129cda8c7ae00e9.png?size=512" alt="Avatar" loading="lazy">
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header">
          <span class="chatlog__author" style="" title="rintaro#0001" data-user-id="296587674737704960">rintaro</span>
          <span class="chatlog__timestamp">02-Oct-18 05:39 AM</span>
        </div>
        <div class="chatlog__content chatlog__markdown">
          <span class="chatlog__markdown-preserve">step out 時の return value キャプチャ は Swift で動かないっぽいんですが、なぜか throw はキャプチャできました。 throws な func の適当なところにブレークポイントはって、ブレークした状態で、 Step out で進めると func 抜けたところで止まります。んで、<span class="chatlog__markdown-pre chatlog__markdown-pre--inline">thread info</span> コマンドを実行すると <span class="chatlog__markdown-pre chatlog__markdown-pre--inline">Return value: (CommandLineSandbox.MyError) $E0 = fooError</span> みたいな行が表示されているので、<span class="chatlog__markdown-pre chatlog__markdown-pre--inline">po $E0</span> とかで中身が見られます。</span>
        </div>
      </div>
    </div>
  </div>
</div>