<div class="chatlog__message-group">
  <div class="chatlog__author-avatar-container">
    <img class="chatlog__author-avatar" src="https://cdn.discordapp.com/avatars/189711109966659584/95280765d1be73ce985dce15ea3585f6.png?size=128" alt="Avatar" loading="lazy">
  </div>
  <div class="chatlog__messages">
    <span class="chatlog__author-name" title="omochimetaru#1122" data-user-id="189711109966659584" style="color: rgb(237,171,161)">omochimetaru</span>
    <span class="chatlog__timestamp">18-Jan-19 07:09 AM</span>
    <div class="chatlog__message " data-message-id="535717344085934081" id="message-535717344085934081" title="Message sent: 18-Jan-19 07:09 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">XCTestCaseでテストメソッドからSwiftの例外を投げると、</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="535717437941743618" id="message-535717437941743618" title="Message sent: 18-Jan-19 07:09 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">XCTestのランタイム側でSwiftのエラーがNSErrorに変換されて？から、コンソールにprintされるらしくて</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="535717527893049344" id="message-535717527893049344" title="Message sent: 18-Jan-19 07:10 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">たとえもとのエラーがCustomStringConvertibleだったとしても、それが表示されないんですけど</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="535717553050484736" id="message-535717553050484736" title="Message sent: 18-Jan-19 07:10 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">みなさんどうしてます？</span>
        </div>
      </div>
    </div>
  </div>
</div>