<div class="chatlog__message-group">
  <div id="chatlog__message-container-634597493983936518" class="chatlog__message-container" data-message-id="634597493983936518">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/338302215078936576/2f0f5d2880a9a7bdc037652fbade2e9a.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(241,196,15)" title="hironytic" data-user-id="338302215078936576">hironytic</span> <a href="/channels/306995750418513920?category=main&amp;channel=swift-2&amp;message_id=634597493983936518"><span class="chatlog__timestamp"></span></a><a href="#chatlog__message-container-634597493983936518">10/18/2019 3:43 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">話がそれちゃうけど、この例のFailureがNeverのときの具体的な型って、next()はthrows付きとthrowsなしの2つがオーバーロードされた感じになってるんですか？それともなしのほうだけになってる？</span></div>
      </div>
    </div>
  </div>
</div>