<div class="chatlog__message-group">
  <div id="chatlog__message-container-905685213756153886" class="chatlog__message-container" data-message-id="905685213756153886">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/291075091025100810/39d60f97ea2bca395f1992c42f25107c.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(155,89,182)" title="kishikawakatsumi#7600" data-user-id="291075091025100810">Kishikawa Katsumi</span> <a href="/channels/291397416043675649?category=開発環境, ライブラリ&amp;channel=server-side&amp;message_id=905685732268572703"><span class="chatlog__timestamp"></span></a><a href="#chatlog__message-container-905685213756153886">11/04/2021 5:09 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve"><code class="chatlog__markdown-pre chatlog__markdown-pre--multiline language-swift">app.get("runner", ":version", "health") { (req) -&gt; EventLoopFuture&lt;Response&gt; in let promise = req.eventLoop.makePromise(of: Response.self) let process = Process() process.executableURL = URL(fileURLWithPath: "/usr/bin/env") process.terminationHandler = { (process) in let status: HTTPResponseStatus = process.terminationStatus == 0 ? .ok : .internalServerError HealthCheckResponse(status: status) .encodeResponse( status: status, headers: HTTPHeaders([("Cache-Control", "no-store")]), for: req ) .cascade(to: promise) } process.launch() return promise.futureResult }</code> 非同期に呼ばれるCallbackクロージャが普通のクロージャで、その中でさらに非同期処理を呼んでいるというコードがあって、コールバックの中でawaitできない、と思ったけど非同期処理の前でいったん値を返して再度awaitする、っていうのでいけた。 合ってるかな？</span></div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-905685732268572703" class="chatlog__message-container" data-message-id="905685732268572703">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="11/04/2021 5:11 AM">05:11</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve"><code class="chatlog__markdown-pre chatlog__markdown-pre--multiline language-swift">app.get("runner", ":version", "health") { (req) -&gt; Response in guard let version = req.parameters.get("version") else { throw Abort(.badRequest) } let process = Process() process.executableURL = URL(fileURLWithPath: "/usr/bin/env") let status: HTTPResponseStatus = await withCheckedContinuation { (continuation) in process.terminationHandler = { (process) in let status: HTTPResponseStatus = process.terminationStatus == 0 ? .ok : .internalServerError continuation.resume(returning: status) } process.launch() } return try await HealthCheckResponse(status: status) .encodeResponse( status: status, headers: HTTPHeaders([("Cache-Control", "no-store")]), for: req ) }</code> こうなった。 <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">encodeResponse</code> がさらに呼んでいる非同期関数で、それは最初のawaitを抜けた後に呼ぶ、というふうに分解してうまくいった、ということ。</span></div>
      </div>
    </div>
  </div>
</div>